spring:
  application:
    name: instr-03
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 10s
