spring:
  application:
    name: instr-04
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    web:
      client:
        max-uri-tags: 20    # 기본 100. 실습이라 작게
