spring:
  application:
    name: instr-01
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 10s          # 기본 60s. 실습이라 짧게
